#!/usr/bin/env python3
from pathlib import Path
import base64,json,mimetypes
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'validated_result/v5';SHOW=OUT/'showcase'
def data(path,mime=None):
 p=Path(path);return f"data:{mime or mimetypes.guess_type(p.name)[0]};base64,"+base64.b64encode(p.read_bytes()).decode()
report=json.loads((OUT/'procedural-v5-report.json').read_text());valid=json.loads((OUT/'v5-release-validation.json').read_text()) if (OUT/'v5-release-validation.json').exists() else {}
video=data(SHOW/'v5_walk_side_60fps.mp4','video/mp4')
imgs={p.stem:data(p,'image/jpeg') for p in SHOW.glob('*.jpg') if not p.name.startswith('_')}
html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Eonwild Tarbosaurus V5 validation</title><style>
:root{{--bg:#07100f;--panel:#111b19;--line:#2a3b35;--text:#f1f5f2;--muted:#9eafa9;--gold:#e9ca76;--green:#8fd3aa}}*{{box-sizing:border-box}}body{{margin:0;background:radial-gradient(circle at 50% -20%,#294238,#08110f 48%,#040807);color:var(--text);font-family:Inter,system-ui,sans-serif}}.wrap{{max-width:1250px;margin:auto;padding:30px 20px 60px}}.eyebrow{{color:var(--gold);font-size:11px;font-weight:850;letter-spacing:.17em;text-transform:uppercase}}h1{{font-size:clamp(30px,5vw,56px);letter-spacing:-.04em;line-height:1;margin:8px 0 12px}}.lead{{color:#c6d1cc;max-width:900px;line-height:1.6}}.status{{display:inline-block;border:1px solid #365647;background:#14261e;color:var(--green);padding:7px 10px;border-radius:999px;font-size:11px;font-weight:800}}.hero,.card{{background:var(--panel);border:1px solid var(--line);border-radius:17px;overflow:hidden;box-shadow:0 20px 65px #0007}}video{{display:block;width:100%;aspect-ratio:16/9;object-fit:contain;background:#e9edec}}.bar{{padding:12px 14px;color:var(--muted);font-size:12px;border-top:1px solid var(--line)}}.metrics{{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:14px 0}}.metric{{background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:14px}}.metric b{{display:block;font-size:25px;color:#fff;letter-spacing:-.03em}}.metric span{{font-size:11px;color:var(--muted)}}.grid{{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}}.card h2{{font-size:15px;margin:0;padding:14px 16px;border-bottom:1px solid var(--line)}}.card img{{width:100%;display:block;background:#e9edec}}.copy{{padding:14px 16px;color:#c5d0cb;line-height:1.55;font-size:13px}}a.btn{{display:inline-block;color:#171b18;background:var(--gold);padding:10px 13px;border-radius:9px;text-decoration:none;font-weight:800;margin:8px 8px 0 0}}a.secondary{{background:#1d2b27;color:#e7edea;border:1px solid #3b5149}}code{{color:#f4dda0}}@media(max-width:900px){{.metrics{{grid-template-columns:repeat(2,1fr)}}.grid{{grid-template-columns:1fr}}}}@media(max-width:520px){{.metrics{{grid-template-columns:1fr 1fr}}}}
</style></head><body><div class="wrap"><div class="eyebrow">Eonwild procedural animation toolkit</div><h1>Tarbosaurus V5</h1><p class="lead">V5 preserves V4's validated planted-foot, terrain, anatomical-leg and root-motion solution, while fixing the visible neutral-mouth error, smoothing secondary tracks, correcting bite closure, rebuilding all authored transitions, and replacing the browser player's double-crossfade behavior with exact handoffs.</p><span class="status">✓ release structure passed · perceptual review required</span><p><a class="btn" href="OPEN_ME_tarbosaurus_v5_3d_browser.html">Open interactive 3D player</a><a class="btn secondary" href="tarbosaurus_procedural_v5_animation_pack.glb">Download animated GLB</a></p>
<section class="hero"><video controls muted loop playsinline preload="metadata" src="{video}"></video><div class="bar">Actual CPU-skinned V5 relaxed walk at 60 FPS. The jaw uses the calibrated 50° living-neutral closure throughout ordinary locomotion.</div></section>
<div class="metrics"><div class="metric"><b>37</b><span>baked animation clips</span></div><div class="metric"><b>75</b><span>skin joints preserved</span></div><div class="metric"><b>50.0°</b><span>calibrated jaw closure</span></div><div class="metric"><b>2.04 mm</b><span>tightest safe witness gap</span></div><div class="metric"><b>16</b><span>endpoint-exact transitions</span></div></div>
<div class="grid">
<section class="card"><h2>V4 → V5 neutral jaw</h2><img src="{imgs['v4_v5_jaw_comparison']}"><div class="copy">V4 used a generic 33° offset and retained a visible gape. V5 selects weighted jaw/skull witnesses from the real 75-joint skin and chooses the tightest non-intersecting neutral closure.</div></section>
<section class="card"><h2>Living-neutral idle</h2><img src="{imgs['v5_idle_keyframes']}"><div class="copy">Breathing, weight shift, head drift, arms and tail remain alive without turning normal respiration into repeated mouth opening.</div></section>
<section class="card"><h2>Eating</h2><img src="{imgs['v5_eat_keyframes']}"><div class="copy">Four staged feeding bites now return to complete neutral closure between cycles. The chew residual is intentionally small and does not leave the mouth hanging open.</div></section>
<section class="card"><h2>Bite attack</h2><img src="{imgs['v5_bite_keyframes']}"><div class="copy">The V4 post-contact re-open bug is removed. V5 reaches a large delivery gape, snaps fully closed at contact, and remains closed through recoil and recovery.</div></section>
<section class="card"><h2>Roar</h2><img src="{imgs['v5_roar_keyframes']}"><div class="copy">The large gape is now exclusive to intentional vocal display. Release returns exactly to the calibrated living-neutral jaw before locomotion resumes.</div></section>
<section class="card"><h2>Transition endpoint audit</h2><img src="{imgs['v5_transition_endpoint_check']}"><div class="copy">Each authored transition ends on the exact first pose of its next clip. The V5 web player commits that endpoint directly and does not apply a second crossfade over it.</div></section>
</div><div class="card" style="margin-top:14px"><h2>What changed in the player</h2><div class="copy"><strong>Buttons now reflect state:</strong> active clips and actions receive visible selection plus <code>aria-pressed</code>. Play/Pause, timeline, sequence state and cancellation stay synchronized. <strong>Artifacts are removed at the runtime boundary:</strong> arbitrary clip selection uses one minimum-jerk snapshot blend with root continuity; authored transition queues use contact-phase scheduling and exact endpoint handoff, never V4's overlapping double fade.</div></div>
</div></body></html>'''
path=OUT/'OPEN_ME_tarbosaurus_v5_validation.html';path.write_text(html);print(path,path.stat().st_size)
